language: python
cache:
  pip: true
  directories: [$HOME/.cache/pre-commit]
dist: bionic
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "nightly"
      env: TOXENV=py38
    - python: "pypy3.6-7.2.0"
      env: TOXENV=pypy3
install: pip install -U tox
script: tox --skip-missing-interpreters false
